name: capcut
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.0.0
  equatable: ^2.0.0
  video_player: ^2.6.1


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - Assets/Rectangle 10123.png
     - Assets/Rectangle 10124.png
     - Assets/Rectangle 39560.png
     - Assets/Rectangle 39563.png
     - Assets/Rectangle 39564.png
     - Assets/Rectangle 39567.png
     - Assets/Group 112901.svg
     - Assets/Rectangle 39561.svg
     - Assets/Group 10975.svg
     - Assets/Rectangle 39530.png
     - Assets/download.svg
     - Assets/Group 10975.svg
     - Assets/bu1.svg
     - Assets/bu2.svg
     - Assets/bu3.svg
     - Assets/Mask group.svg
     - Assets/mic.svg
     - Assets/music-note.svg
     - Assets/Group 10991.svg
     - Assets/Group 112232.svg
     - Assets/Repeate 3.svg
     - Assets/Repeate 4.svg
     - Assets/Rectangle 39524.svg
     - Assets/Rectangle 39521.svg
     - Assets/Rectangle 39539.svg
     - Assets/Rectangle 39539.svg
     - Assets/Rectangle 39526.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
